# download the binaries with unarchive but we want to checksum them
# - name: Unarchive the Consul and Vault binaries archived
#   ansible.builtin.unarchive:
#     src: "{{ item }}"
#     dest: /usr/bin
#     remote_src: yes
#   with_items:
#     - "{{ consul_download_url }}"
#     - "{{ vault_download_url }}"

- name: Download the files
  get_url:
    url: "{{ item }}"
    dest: /tmp
    mode: '0440'
  with_items:
    - "{{ consul_download_url }}"
    - "{{ consul_download_url | regex_replace('_linux_.*.zip', '_SHA256SUMS') }}"
    - "{{ consul_download_url | regex_replace('_linux_.*.zip', '_SHA256SUMS.sig') }}"
    - "{{ vault_download_url }}"
    - "{{ vault_download_url | regex_replace('_linux_.*.zip', '_SHA256SUMS') }}"
    - "{{ vault_download_url | regex_replace('_linux_.*.zip', '_SHA256SUMS.sig') }}"

- name: copy hashicorp.asc to /tmp
  copy:
    src: hashicorp.asc
    dest: /tmp/hashicorp.asc
    mode: '0440'

- name: import HashiCorp GPG key
  command: gpg --import /tmp/hashicorp.asc