# set_hostname and download consul and vault binaries
- hosts: targets
  become: yes

  roles:
    - set_hostname
    - downloads

# consul create TLS CA and certs for cluster
- hosts: targets[0]
  become: yes

  roles:
    - consul_create_tls

# consul cluster config with default acl
- hosts: targets
  become: yes

  roles:
    - consul_cluster_config

# consul bootstrap ACL for cluster
- hosts: targets[0]
  become: yes

  roles:
    - consul_bootstrap_acl

# consul register services
- hosts: targets
  become: yes

  roles:
    - consul_register_services